### PR TITLE
Refactors ApplyFilter from belonging to DicomFile to DicomFilter

### PR DESCRIPTION
**Pull request by cppcooper**

### CODE REVIEW

**Comment by brianzhouzc** [comment]
Plugin does not load. Error message:
`Error /usr/share/orthanc/plugins/data-anonymizer.so: undefined symbol: _ZN11DicomFilter11ApplyFilterER9DicomFile`
Something wrong with CMake?

**Comment by cppcooper** [comment]
> Plugin does not load. Error message: `Error /usr/share/orthanc/plugins/data-anonymizer.so: undefined symbol: _ZN11DicomFilter11ApplyFilterER9DicomFile` Something wrong with CMake?

I presume you haven't reloaded your cmake, or need to delete your files. You should post more context to your error messages though. I'm like 99% sure that's a compiler error, but I don't know for sure cause there's no proper context for the error.
The plugin loads on my machine, and obviously on the remote as well

**Comment by brianzhouzc** [comment]
Reloading CMake did the trick. Was confused as it builds with no error. Can merge when ready

**Comment by cppcooper** [comment]
weird, it should have failed at linking.. at the very least

**Pull request merged**
